export const schs = [
  { name: 'Abia State University', abbreviation: 'ABSU' },
  { name: 'Achievers University', abbreviation: 'AU' },
  { name: 'Adekunle Ajasin University', abbreviation: 'AAUA' },
  { name: 'Adeleke University', abbreviation: 'AU' },
  { name: 'Afe Babalola University', abbreviation: 'ABUAD' },
  {
    name: 'African University of Science and Technology',
    abbreviation: 'AUST',
  },
  { name: 'Ahmadu Bello University', abbreviation: 'ABU' },
  { name: 'Ajayi Crowther University', abbreviation: 'ACU' },
  { name: 'Akanu Ibiam Federal Polytechnic', abbreviation: 'AIFPOLY' },
  { name: 'Akwa Ibom State University', abbreviation: 'AKSU' },
  { name: 'Al-Hikmah University', abbreviation: 'AHU' },
  { name: 'Al-Qalam University', abbreviation: 'AQU' },
  { name: 'Alcorn State University Nigeria', abbreviation: 'ASUN' },
  {
    name: 'Alex Ekwueme Federal University Ndufu-Alike',
    abbreviation: 'AE-FUNAI',
  },
  { name: 'American University of Nigeria', abbreviation: 'AUN' },
  { name: 'Anchor University', abbreviation: 'AU' },
  { name: 'Arthur Jarvis University', abbreviation: 'AJU' },
  { name: 'Auchi Polytechnic', abbreviation: 'AUCHIPOLY' },
  { name: 'Augustine University', abbreviation: 'AU' },
  { name: 'Bayero University Kano', abbreviation: 'BUK' },
  { name: 'Baze University', abbreviation: 'BU' },
  { name: 'Bells University of Technology', abbreviation: 'BELLSTECH' },
  { name: 'Benson Idahosa University', abbreviation: 'BIU' },
  { name: 'Benue State University', abbreviation: 'BSU' },
  { name: 'Bingham University', abbreviation: 'BU' },
  { name: 'Borno State University', abbreviation: 'BOSU' },
  { name: 'Bowen University', abbreviation: 'BU' },
  { name: 'Caleb University', abbreviation: 'CU' },
  { name: 'Caritas University', abbreviation: 'CU' },
  { name: 'Chrisland University', abbreviation: 'CU' },
  { name: 'Christopher University', abbreviation: 'CU' },
  { name: 'Cliff University', abbreviation: 'CU' },
  { name: 'Coal City University', abbreviation: 'CCU' },
  { name: 'Covenant University', abbreviation: 'CU' },
  { name: 'Crawford University', abbreviation: 'CU' },
  { name: 'Crescent University', abbreviation: 'CU' },
  { name: 'Crown Hill University', abbreviation: 'CHU' },
  { name: 'Cruise University', abbreviation: 'CU' },
  { name: 'Delta State University', abbreviation: 'DELSU' },
  { name: 'Dominican University', abbreviation: 'DU' },
  { name: 'Ebonyi State University', abbreviation: 'EBSU' },
  { name: 'Ecode Polytechnic', abbreviation: 'ECODEPOLY' },
  { name: 'Edo State Polytechnic', abbreviation: 'EDOPOLY' },
  { name: 'Edo University Iyamho', abbreviation: 'EUI' },
  { name: 'Edwin Clark University', abbreviation: 'ECU' },
  { name: 'Ekiti State University', abbreviation: 'EKSU' },
  {
    name: 'Enugu State University of Science and Technology',
    abbreviation: 'ESUT',
  },
  { name: 'Eruku Polytechnic', abbreviation: 'ERUKUPOLY' },
  { name: 'Eso-Oko Polytechnic', abbreviation: 'ESOPOLY' },
  { name: 'Evan University', abbreviation: 'EU' },
  {
    name: 'Federal College of Education (Technical) Omoku',
    abbreviation: 'FCETOMOKU',
  },
  { name: 'Federal Polytechnic Ado Ekiti', abbreviation: 'FEDPOLADOEKITI' },
  { name: 'Federal Polytechnic Auchi', abbreviation: 'FEDPOLAUCHI' },
  { name: 'Federal Polytechnic Bida', abbreviation: 'FEDPOLBIDA' },
  { name: 'Federal Polytechnic Idah', abbreviation: 'FEDPOLIDAH' },
  { name: 'Federal Polytechnic Ile-Oluji', abbreviation: 'FEDPOLILOOLUJI' },
  { name: 'Federal Polytechnic Kaura Namoda', abbreviation: 'FEDPOLKN' },
  { name: 'Federal Polytechnic Mubi', abbreviation: 'FEDPOLMUBI' },
  { name: 'Federal Polytechnic Nasarawa', abbreviation: 'FEDPOLNASARAWA' },
  { name: 'Federal Polytechnic Nekede', abbreviation: 'FEDPOLNEKEDE' },
  { name: 'Federal Polytechnic Offa', abbreviation: 'FEDPOLOFFA' },
  { name: 'Federal Polytechnic Oko', abbreviation: 'FEDPOLOKO' },
  {
    name: 'Federal University of Agriculture Abeokuta',
    abbreviation: 'FUNAAB',
  },
  {
    name: 'Federal University of Petroleum Resources Effurun',
    abbreviation: 'FUPRE',
  },
  { name: 'Federal University of Technology Akure', abbreviation: 'FUTA' },
  { name: 'Federal University of Technology Minna', abbreviation: 'FUTMINNA' },
  { name: 'Federal University of Technology Owerri', abbreviation: 'FUTO' },
  { name: 'Federal University Dutse', abbreviation: 'FUD' },
  { name: 'Federal University Dutsin-Ma', abbreviation: 'FUD' },
  { name: 'Federal University Gusau', abbreviation: 'FUGUSAU' },
  { name: 'Federal University Kashere', abbreviation: 'FUK' },
  { name: 'Federal University Lafia', abbreviation: 'FULAFIA' },
  { name: 'Federal University Lokoja', abbreviation: 'FUL' },
  { name: 'Federal University Ndufu-Alike Ikwo', abbreviation: 'FUNAI' },
  { name: 'Federal University Otuoke', abbreviation: 'FUO' },
  { name: 'Federal University Oye-Ekiti', abbreviation: 'FUOYE' },
  { name: 'Federal University Wukari', abbreviation: 'FUW' },
  { name: 'Fountain University', abbreviation: 'FU' },
  { name: 'Gombe State University', abbreviation: 'GSU' },
  { name: 'Godfrey Okoye University', abbreviation: 'GOU' },
  { name: 'Gregory University Uturu', abbreviation: 'GUU' },
  { name: 'Hezekiah University', abbreviation: 'HU' },
  { name: 'Honeywell University', abbreviation: 'H' },

  { name: 'Honeywell University', abbreviation: 'HU' },
  { name: 'Ibrahim Badamasi Babangida University', abbreviation: 'IBBU' },
  { name: 'Ignatius Ajuru University of Education', abbreviation: 'IAUE' },
  { name: 'Imo State University', abbreviation: 'IMSU' },
  { name: 'Joseph Ayo Babalola University', abbreviation: 'JABU' },
  { name: 'Kaduna State University', abbreviation: 'KASU' },
  {
    name: 'Kano State University of Science and Technology',
    abbreviation: 'KASUSTECH',
  },
  { name: 'Katsina State University', abbreviation: 'KSU' },
  {
    name: 'Kebbi State University of Science and Technology',
    abbreviation: 'KSUSTA',
  },
  { name: 'Kings University', abbreviation: 'KU' },
  { name: 'Kogi State University', abbreviation: 'KSU' },
  { name: 'Kwara State University', abbreviation: 'KWASU' },
  { name: 'Lagos State Polytechnic', abbreviation: 'LASPOTECH' },
  { name: 'Lagos State University', abbreviation: 'LASU' },
  { name: 'Landmark University', abbreviation: 'LMU' },
  { name: 'Lead City University', abbreviation: 'LCU' },
  { name: 'Legacy University', abbreviation: 'LU' },
  { name: 'Madonna University Nigeria', abbreviation: 'MUN' },
  { name: 'Maritime University', abbreviation: 'MU' },
  { name: 'Mcpherson University', abbreviation: 'MU' },
  { name: 'Michael Okpara University of Agriculture', abbreviation: 'MOUAU' },
  { name: 'Micheal and Cecilia Ibru University', abbreviation: 'MCIU' },
  { name: 'Modibbo Adama University of Technology', abbreviation: 'MAUTECH' },
  { name: 'Mountain Top University', abbreviation: 'MTU' },
  { name: 'Nnamdi Azikiwe University', abbreviation: 'NAU' },
  { name: 'Nigerian Army University Biu', abbreviation: 'NAUB' },
  { name: 'Nigerian Defence Academy', abbreviation: 'NDA' },
  { name: 'Nigerian Maritime University', abbreviation: 'NMU' },
  { name: 'Nigerian Turkish Nile University', abbreviation: 'NTNU' },
  { name: 'Nizamiye University', abbreviation: 'NU' },
  { name: 'Nnamdi Azikiwe University Awka', abbreviation: 'UNIZIK' },
  { name: 'Novena University', abbreviation: 'NU' },
  { name: 'Obafemi Awolowo University', abbreviation: 'OAU' },
  { name: 'Oduduwa University', abbreviation: 'OU' },
  { name: 'Olabisi Onabanjo University', abbreviation: 'OOU' },
  { name: 'Ondo State University of Medical Sciences', abbreviation: 'OSUMS' },
  {
    name: 'Ondo State University of Science and Technology',
    abbreviation: 'OSUSTECH',
  },
  { name: 'Osun State University', abbreviation: 'UNIOSUN' },
  {
    name: "Our Saviour's Institute of Science and Technology",
    abbreviation: 'OSIST',
  },
  { name: 'Oyo State Technical University', abbreviation: 'OTECHU' },
  { name: 'Pan-Atlantic University', abbreviation: 'PAU' },
  { name: 'Paul University', abbreviation: 'PU' },
  { name: 'Plateau State University', abbreviation: 'PLASU' },
  { name: 'Precious Cornerstone University', abbreviation: 'PCU' },
  { name: "Redeemer's University", abbreviation: 'RUN' },
  { name: 'Renaissance University', abbreviation: 'RU' },
  { name: 'Rhema University', abbreviation: 'RU' },
  { name: 'Rivers State University', abbreviation: 'RSU' },
  { name: 'Salem University', abbreviation: 'SU' },
  { name: 'Samuel Adegboyega University', abbreviation: 'SAU' },
  { name: 'Sokoto State University', abbreviation: 'SSU' },
  {
    name: 'Southern African University of Applied Sciences',
    abbreviation: 'SAUAS',
  },
  { name: 'Spiritan University', abbreviation: 'SU' },
  { name: 'Summit University', abbreviation: 'SU' },
  { name: 'Sule Lamido University', abbreviation: 'SLU' },
  { name: 'Tansian University', abbreviation: 'TU' },
  { name: 'Taraba State University', abbreviation: 'TSU' },
  { name: 'The Nigerian Turkish Nile University', abbreviation: 'NTNU' },
  { name: 'Triumph University', abbreviation: 'TU' },
  { name: "Umaru Musa Yar'adua University", abbreviation: 'UMYU' },
  { name: 'Usmanu Danfodiyo University', abbreviation: 'UDUS' },
  { name: 'University of Abuja', abbreviation: 'UNIABUJA' },
  { name: 'University of Africa', abbreviation: 'UA' },
  { name: 'University of Agriculture Makurdi', abbreviation: 'UAM' },
  { name: 'University of Benin', abbreviation: 'UNIBEN' },
  { name: 'University of Calabar', abbreviation: 'UNICAL' },
  { name: 'University of Ilorin', abbreviation: 'UNILORIN' },
  { name: 'University of Jos', abbreviation: 'UNIJOS' },
  { name: 'University of Lagos', abbreviation: 'UNILAG' },
  { name: 'University of Maiduguri', abbreviation: 'UNIMAID' },
  { name: 'University of Mkar', abbreviation: 'UNIMKA' },
  { name: 'University of Nigeria Nsukka', abbreviation: 'UNN' },
  { name: 'University of Port Harcourt', abbreviation: 'UNIPORT' },
  { name: 'University of Uyo', abbreviation: 'UNIUYO' },
  { name: 'Veritas University', abbreviation: 'VU' },
  { name: 'Wellspring University', abbreviation: 'WU' },
  { name: 'Western Delta University', abbreviation: 'WDU' },
  { name: 'Yobe State University', abbreviation: 'YSU' },
  { name: 'Yusuf Maitama Sule University', abbreviation: 'YMSU' },
];
